version: '3.9'  # Указывает версию файла конфигурации Docker Compose. Здесь используется версия 3.9.

services:  # Раздел, в котором перечислены все сервисы (контейнеры), которые Compose должен запустить.

  calc-java:  # Сервис для Java калькулятора.
    build:  # Указывает, как будет собран Docker-образ для этого сервиса.
      context: ./calc-java  # Указывает директорию (./calc-java), где находится Dockerfile и другие файлы для сборки образа.
    container_name: calc-java  # Устанавливает имя контейнера как "calc-java".
    stdin_open: true  # Открывает стандартный ввод для контейнера (полезно для интерактивных приложений).
    tty: true  # Позволяет контейнеру работать в терминале с возможностью отображения текста и ввода.

  game-java:  # Сервис для Java игры.
    build:  # Указывает, как будет собран Docker-образ для этого сервиса.
      context: ./game-java  # Указывает директорию для сборки Docker-образа.
    container_name: game-java  # Устанавливает имя контейнера как "game-java".
    stdin_open: true  # Открывает стандартный ввод для контейнера.
    tty: true  # Позволяет работать в терминале.

  calc-py:  # Сервис для Python калькулятора.
    build:  # Указывает, как будет собран Docker-образ для этого сервиса.
      context: ./calc-py  # Указывает директорию для сборки Docker-образа.
    container_name: calc-py  # Устанавливает имя контейнера как "calc-py".
    stdin_open: true  # Открывает стандартный ввод для контейнера.
    tty: true  # Позволяет работать в терминале.

  rpsgame-py:  # Сервис для Python игры "Камень, ножницы, бумага".
    build:  # Указывает, как будет собран Docker-образ для этого сервиса.
      context: ./rpsgame-py  # Указывает директорию для сборки Docker-образа.
    container_name: rpsgame-py  # Устанавливает имя контейнера как "rpsgame-py".
    stdin_open: true  # Открывает стандартный ввод для контейнера.
    tty: true  # Позволяет работать в терминале.

  dart-calc:  # Сервис для калькулятора на языке Dart.
    build:  # Указывает, как будет собран Docker-образ для этого сервиса.
      context: ./dart-calc  # Указывает директорию для сборки Docker-образа.
    container_name: dart-calc  # Устанавливает имя контейнера как "dart-calc".
    stdin_open: true  # Открывает стандартный ввод для контейнера.
    tty: true  # Позволяет работать в терминале.

  site:  # Сервис для веб-сайта.
    build:  # Указывает, как будет собран Docker-образ для этого сервиса.
      context: ./site  # Указывает директорию для сборки Docker-образа.
    container_name: site  # Устанавливает имя контейнера как "site".
    ports:  # Открытие портов для контейнера.
      - "8080:80"  # Пробрасывает порт 8080 на хосте к порту 80 внутри контейнера. Это позволяет доступ к веб-сайту на хосте по адресу http://localhost:8080.
